// Generated by OABuilder
package com.oreillyauto.storepurchaseorder.remote;

import com.viaoa.remote.annotation.OARemoteInterface;
import com.oreillyauto.storepurchaseorder.model.oa.api.*;

@OARemoteInterface
public interface APIInterface {
}
